### ISSUE TITLE
Problems installing on Python2.7

### ISSUE THREAD

**Issue by willmcgugan** [althonos/fs.sshfs#13]
Hi @althonos 

I'm struggling to install fs.sshfs on Python2.7.  I get the following error when importing...

```
>>> import fs.sshfs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named sshfs
```

Although bizarrely I see `ssh` and `sftp` in the list of openers.

Everything appears to work fine on Python3

Suspect this may be related to https://github.com/althonos/fs.sshfs/issues/12

I've tried upgrading `setuptools` and `distribute`, but no luck.

Let me know if I can help with the debugging.

**Comment by althonos** [comment]
Well, I'm not sure, since #12 error shows that the `ssh` opener is not recognised.

Are you sure you don't have `fs` installed in editable mode ? It screws up with namespace packages.

**Comment by willmcgugan** [comment]
I did have fs in editable mode! Works fine now.
