### ISSUE TITLE
 v2.1.0 of fs was released

### ISSUE THREAD

**Issue by ReimarBauer** [althonos/fs.sshfs#19]
Hi
there is a  build rule fs ~=2.1.0 and v2.1.0 of fs was released

Are there known issues?

regards
Reimar

**Comment by althonos** [comment]
Hi,

fs `v2.1` is not strictly incompatible with fs `v2.0`, but I want to fix #17 (with issues introduced earlier than `v2.1` before releasing a new version).

**Comment by althonos** [comment]
Fixed with `v0.9.0`.
