### ISSUE TITLE
working with files..

### ISSUE THREAD

**Issue by worknlearn** [althonos/fs.sshfs#24]
This would be rather an incompetence on my part than an issue reporting, but I spent last 6 hours and still cannot figure out how to move(copy) files in and out of my SFTP directory.

I did manage to get into SFTP directory, 

my_fs = SSHFS("OO.22.167.217", user="1234", passwd="111", timeout=10, port=25761, keepalive=10, compress=False)
print(my_fs)
a = my_fs.listdir('/qwe')
print(a)

['111.txt', 'demo3.py', 'handout.pdf']

This indeed prints out items in the root! ..but I'm stuck here for hours.
Would you be kind enough to post a snippet of scripts, moving c:\111.txt to my_fs?

(..found a negligible typo: paswd should be passwd.)

**Comment by althonos** [comment]
Hi @worknlearn,
you opened the remote filesystem, but you also need to open a local filesystem to move things between them ! Here's an example that'll move `C:\\example.txt` to your remote machine:

```python
import fs.copy
from fs.sshfs import SSHFS
from fs.osfs import OSFS

with SSHFS("00.22.167.217", user="1234", passwd="111") as remote:  # you can add more parameters
    with OSFS("C:\\") as local:
        fs.copy.copy_file(local, "exemple.txt", remote, "exemple.txt")  # you can change the name of the remote file
```

`SSHFS` is a Pyfilesystem, so it implements all the methods you could find in [the documentation](https://docs.pyfilesystem.org/en/latest/) !

**Comment by worknlearn** [comment]
I finally got it, thank you. Is importing from SFTP server also possible? I read the documentation (and re-read a couple more times), I learned that the original Pyfilesystem has "fs.expose.importhook" feature, which is not compatible with python 3(which I am using.), so I tried Pyfilesystem1 + fs.sshfs combination and that didn't work out (I later discovered the terminal spells it out "fs.sshfs requires fs 2.2.0" at the time of pip installation.)

I'm again stuck here I would appreciate if you could shed some light on this, thank you Martin.

**Comment by althonos** [comment]
Are you simply trying to download files from your server ? Then this will work:
```python
with SSHFS("00.22.167.217", user="1234", passwd="111") as remote: 
    with OSFS("C:\\") as local:
        fs.copy.copy_file(remote, "exemple.txt", local, "exemple.txt")  # i just switched source and destination filesystem
```

`fs.sshfs` only works with Pyfilesystem2. It has so many changes compared to Pyfilesystem1 it is basically a whole different library at that point.
