### ISSUE TITLE
Feature Request: Expose missing host key policy as a parameter

### ISSUE THREAD

**Issue by efuce** [althonos/fs.sshfs#27]
Hello,

We are trying to implement validation of host keys against a whitelist of known hosts keys, and would be interested in the ability to change the missing host key policy to something other than AutoAddPolicy. Would it be possible to add such an option?

**Comment by althonos** [comment]
Hi @efuce , sorry for the delay, starting from `v0.13.0` you can pass an arbitrary `paramiko.MissingHostKeyPolicy` instance to `SSHFS.__init__` with the `policy` argument. Cheers!
