### ISSUE TITLE
Mount remote filesystem to local

### ISSUE THREAD

**Issue by sree80** [althonos/fs.sshfs#29]
Hi,

I am trying to mount a remote filesystem to my local server. I don't see any example online.
I tried few things and not getting the correct result.

can anyone please share an example with me.

Highly appreciate any info!!!

**Comment by althonos** [comment]
Hi, you're most likely confusing this library with the FUSE [`sshfs`](https://github.com/libfuse/sshfs).

**Comment by sree80** [comment]
thank you
