### ISSUE TITLE
Find the latest file on a remote Server

### ISSUE THREAD

**Issue by sree80** [althonos/fs.sshfs#30]
Here is my  scenario -

i have files on a remote server in a certain directory and I want to loop thru this remote server and directory and identify the latest files. I want to pass a file name as a wildcard and for that specified file name, it has to loop the remote server and directory and return the latest file.

The documentation -- https://pyfilesystem2.readthedocs.io/en/latest/
doesn't list this specific scenario. and  i am looking for some example on how to do it.

any information is highly appreciated !!!!

**Comment by althonos** [comment]
Hi @sree80, here is a snippet that will work for any filesystem:
```python

myfs = fs.open_fs("...")

# this is where you pass your directory path and glob -> filterdir returns a generator
# (the 'details' namespace makes Pyfilesystem query the atime/mtime/ctime of the file)
files = myfs.filterdir("/some/path", files=["*.py"], namespaces=["basic", "details"])   

# we find the file with the largest modification time 
# (use `f.accessed` to sort by atime or `f.created` by ctime)
latest_file = max(files, key=lambda f: f.modified)
```

**Comment by sree80** [comment]
thanks so much. highly appreciate your help !!!
