### ISSUE TITLE
SFTP URLs?

### ISSUE THREAD

**Issue by lurch** [althonos/fs.sshfs#31]
Looking at https://github.com/althonos/fs.sshfs/blob/master/setup.cfg#L61 it seems this module supports both `ssh` and `sftp` openers. Does that mean `my_fs = fs.open_fs("sftp://[user[:password]@]host[:port]/[directory]")` is also valid? Maybe that should be mentioned in the README? :man_shrugging:

**Comment by althonos** [comment]
Indeed it should be! I'll add that to the README.
