### ISSUE TITLE
Timeout handling on exotic SFTP servers

### ISSUE THREAD

**Issue by bartekre** [althonos/fs.sshfs#39]
Hello,

Recently we've started working with Syncplify.me server. Apparently, it doesn't send an EOF which makes commands like `listdir` raise a timeout. This seems related to #15, but since it happens every time, we needed to work it around.
The problem has also been reported directly in Paramiko's tracker (see https://github.com/paramiko/paramiko/issues/109) and apparently it also applies to Windows 10 OpenSSH implementation.
Currently I made a wrapper which forces `stdout` and `stderr` buffers to get closed by the client after reaching a certain timeout (based on a workaround posted here: https://github.com/paramiko/paramiko/issues/109#issuecomment-111621658). Here's my approach: https://github.com/pylogy/fs.sshfs/tree/fix-exec-timeout (it feels a bit hackish, so I haven't posted a PR yet). I'm also considering adding this directly to Paramiko after figuring out where exactly it should be handled.

**Comment by althonos** [comment]
Hi ! Thanks for reporting this and taking the time to identify the issue. I wouldn't be opposed to adding the hotfix you proposed until `paramiko` developers can address the issue. 

My only question is how much it makes sense to add another argument user-wise: wouldn't an user expect the timeout to also apply to the `exec` calls? If there is a good reason not to use the global timeout, I could agree with adding it as an additional kwarg; right now I'm more thinking about semver compatibility for adding an argument and eventually removing it when `paramiko` itself is fixed.

**Comment by bartekre** [comment]
Yes, I think in typical setup it's good enough to use the _regular_ `timeout`.

However, in our setup this would be a bit inconvenient. Since we're working on a setup in which several hundred thousand small files may be located in the same directory, the timeouts for listings need to be set to fairly large values (currently 120s). If use the same value for `_exec_command`, it would take 480s to get the platform name (because we need to exceed the timeout on `stderr` and `stdout` for both `uname -s` and `sysinfo`). This would have a significant impact on the overall processing time since the server tends to reconnect and platform needs to be fetched once more. 

I wonder if we could use the regular `timeout` as the default for `_exec_command`, but keep the option of setting a `exec-timeout` in special cases.

If that's ok, I'll adjust my code and make a PR.

**Comment by althonos** [comment]
That would be fine indeed, with `exec_timeout=None` taking the `timeout` value if not other value is provided. The example you describe is also quite reasonable IMO.

**Comment by althonos** [comment]
Hi @bartekre , sorry for the delay, starting from `v0.13.0` there is now an `exec_timeout` argument to the `SSHFS` constructor that does what we discussed. Cheers!

**Comment by bartekre** [comment]
Thanks! I'll update my install this week and let you know how it performs in the wild.
