### ISSUE TITLE
platform any but not windows currently?

### ISSUE THREAD

**Issue by ReimarBauer** [althonos/fs.sshfs#4]
I am not sure if it is possible to run this from windows. At least momently appveyor cries about pwd and grp. I was not able to verify this before I was able to use the conda-forge CIs.

If that principle is possiple then may be moving the imports 
after

`if self.platform in Platform.Unix`

solves it?

or if that is only optional needed info['access'] may be excluded for windows
```
 if 'access' in namespaces:
            info['access'] = self._make_access_from_stat(stat_result)
```
but the imports have to be moved too, or enclosed by an exception.

https://anaconda.org/conda-forge/paramiko seems to be a valid windows package.

**Comment by althonos** [comment]
I'm not happy with the platform management currently. I'll try to fix that soon.

**Comment by ReimarBauer** [comment]
Perfect. I will update the recipe after it is fixed.

**Comment by althonos** [comment]
I realised I was using `pwd` and `grp` because I was too lazy to write a simple 3-lines function to parse a `getent` result. This is done now, so `grp` and `pwd` are not imported anymore. I'll try to see if I can setup an Appveyor, but this may be tricky since tests use `docker`.

**Comment by ReimarBauer** [comment]
That is much better now. Half of it works with windows, also it can be builded on conda-forge, but I think I wait with the next trial there. 

It works with

```
from fs.sshfs import SSHFS
my_fs = SSHFS(
  host, user=None, paswd=None, pkey=None, timeout=10, port=22,
  keepalive=10, compress=False, config_path='~/.ssh/config'
)
```

But didn't with the opener, I found for the option 
```
import fs
my_fs = fs.open_fs("ssh://[user[:password]@]host[:port]/[directory]")
```
this problem.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\test\Miniconda2\envs\fsenv\lib\site-packages\fs\opener\regist
ry.py", line 179, in open_fs
    default_protocol=default_protocol
  File "C:\Users\test\Miniconda2\envs\fsenv\lib\site-packages\fs\opener\regist
ry.py", line 138, in open
    opener = self.get_opener(protocol)
  File "C:\Users\test\Miniconda2\envs\fsenv\lib\site-packages\fs\opener\regist
ry.py", line 89, in get_opener
    exception
  File "C:\Users\test\Miniconda2\envs\fsenv\lib\site-packages\six.py", line 71
8, in raise_from
    raise value
fs.opener.errors.EntryPointError: could not load entry point; The 'configparser~
=3.2' distribution was not found and is required by the application
```

**Comment by ReimarBauer** [comment]
btw. I like this idea very much!!!

**Comment by ReimarBauer** [comment]
Uh, my fault. I can fix that in the recipe, I missed to add just configparster.

**Comment by althonos** [comment]
Yes, sorry, I'm using configparser to parse the FS URL parameters, but since the Python 2 version is limited, I ended up using the backport.

**Comment by ReimarBauer** [comment]
seems to work with my local test setup

**Comment by althonos** [comment]
@ReimarBauer : closing this since it seems to work fine for now. I'll open another issue about setting up an AppVeyor.
