### ISSUE TITLE
Unsupported SSH connection when using PyInstaller

### ISSUE THREAD

**Issue by prodangp** [althonos/fs.sshfs#42]
I am connecting via SSH using fs.sshfs like this,

`my_fs = fs.open_fs(u'ssh://myuser:mypassword@my.server.com:22/share/directory/')`

It is working fine when I run the script using PyCharm. However, when I create my EXE using PyInstaller and I run the executable I get this error:

`fs.opener.errors.UnsupportedProtocol: protocol 'ssh' is not supported`

I think that the PyInstaller doesn't include fs.sshfs and I have tried also to run PyInstaller with the following option:

` --hidden-import=fs.sshfs `

The error persists.

**Comment by althonos** [comment]
Ah yes, I've run into something similar with PyInstaller, where it doesn't play well with the `setuptools` entry points that I made for Pyfilesystem2 to load external filesystem openers.

If you can register the SSHFS opener somewhere manually with the code below, PyInstaller should be able to pick it in the EXE:
```python
import fs.opener
import fs.opener.sshfs

fs.opener.registry.install(fs.opener.sshfs.SSHOpener)
```

**Comment by prodangp** [comment]
It works now. Thank you!

**Comment by althonos** [comment]
Cool! Will close the issue, since this is really a PyInstaller bug. I guess they are aware of it (pyinstaller/pyinstaller#1188) but it does not look they are working on a fix (or even know how to fix it).
