### ISSUE TITLE
Handle parameters passed in through opener URL (such as ssh://user@host?compress=True)

### ISSUE THREAD

**Issue by jotaf98** [althonos/fs.sshfs#50]
Hi, I'd like to let the user pass in parameters through the opener URL, as described here:

https://docs.pyfilesystem.org/en/latest/openers.html

However, since they are all treated as strings, this is not supported. However it seems like it could be relatively easy to convert strings to the expected type (bool, int)?

**Comment by althonos** [comment]
Actually if you use the latest version of `fs.sshfs` you can do that already: check the code for the opener, it supports reading some parameters as `int` or `bool` if needed.

https://github.com/althonos/fs.sshfs/blob/413e70b4bb2044e41a83b6e93f5e7fbf308b7b70/fs/opener/sshfs.py#L38-L50

**Comment by jotaf98** [comment]
Right, it should work with the latest version yes -- I should have investigated it better before reporting, sorry for the noise.

**Comment by jotaf98** [comment]
Also thanks for creating fs.sshfs -- it really helped with a [project](https://github.com/jotaf98/overboard) where most servers are accessed through SSH and there are no guarantees about any other kind of access :)

**Comment by althonos** [comment]
Happy to hear that! :partying_face:
