### ISSUE TITLE
TypeError: move() got an unexpected keyword argument 'preserve_time'

### ISSUE THREAD

**Issue by bourriquet** [althonos/fs.sshfs#51]
Since updating `PyFilesystem2` to `2.4.14`, I get `TypeError: move() got an unexpected keyword argument 'preserve_time'` on `SSHFS.move()`

The `preserve_time` keyword was introduced to `move` in `PyFilesystem2==2.4.14`

**Comment by althonos** [comment]
Fixed in `v1.0.1`. Thanks for the report!
