### ISSUE TITLE
Release 0.6.2 available?

### ISSUE THREAD

**Issue by genben** [althonos/fs.sshfs#6]
Martin,

Is it possible to release v.0.6.2?
The current version 0.6.1 on PYPI doesn't include the commit 23a3f9f31ad6ff8e1e4150db011045f73cad4d52 (Change remote platfrom management).

As a result, it is not possible to use it on Windows without because of missing modules `pwd` and `grp`.

Best regards,
Gennady

**Comment by althonos** [comment]
Hi Gennady,
I released [`v0.7.0`](https://pypi.python.org/pypi/fs.sshfs) this morning. 
The new version also brings FS URLs extraction but adds a new dependency on Python 2 (`configparser`).

**Comment by genben** [comment]
Thank you Martin.
